services:
  - type: web
    name: fiscal-web
    env: python
    buildCommand: "pip install -r requirements.txt && python3 manage.py collectstatic --noinput"
    startCommand: "gunicorn config.wsgi"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: fiscal-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4

databases:
  - name: fiscal-db
    databaseName: fiscal_db
    user: fiscal_user