# Generated by Django 5.2.4 on 2025-07-16 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0003_remove_cliente_usuario_asignado_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='direccion_fiscal',
            new_name='domicilio',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='email_contacto',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='telefono_contacto',
        ),
        migrations.AddField(
            model_name='cliente',
            name='areas',
            field=models.CharField(blank=True, max_length=255, verbose_name='Áreas'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Correo'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='estatus',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='cliente',
            name='fecha_inicio_operaciones',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de inicio de operaciones'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='forma_de_pago',
            field=models.CharField(blank=True, max_length=100, verbose_name='Forma de Pago'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='giro_comercial',
            field=models.CharField(blank=True, max_length=200, verbose_name='Giro Comercial'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='honorarios',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='cliente',
            name='no_recurrente',
            field=models.CharField(blank=True, max_length=50, verbose_name='No. Recurrente'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='socio',
            field=models.CharField(blank=True, max_length=255, verbose_name='Socio'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, verbose_name='Teléfono'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='tipo',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='cliente',
            name='tipo_de_servicio',
            field=models.CharField(blank=True, max_length=200, verbose_name='Tipo de servicio'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='regimen_fiscal',
            field=models.CharField(blank=True, max_length=200, verbose_name='Régimen Fiscal'),
        ),
    ]
