# Generated by Django 5.2.4 on 2025-07-23 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0005_cuestionario_pregunta_opcion_resultadocuestionario'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='valor',
            field=models.PositiveIntegerField(default=1, help_text='Puntos que vale esta pregunta.'),
        ),
    ]
