# Generated by Django 5.2.4 on 2025-07-23 03:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0006_pregunta_valor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuestionarios_asignados', models.ManyToManyField(blank=True, to='contabilidad.cuestionario')),
                ('modulos_permitidos', models.ManyToManyField(blank=True, related_name='usuarios_con_acceso', to='contabilidad.modulo')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
