# Generated by Django 5.2.4 on 2025-07-23 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0007_perfilusuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilusuario',
            name='cuestionarios_asignados',
        ),
        migrations.AddField(
            model_name='modulo',
            name='cuestionarios',
            field=models.ManyToManyField(blank=True, to='contabilidad.cuestionario'),
        ),
    ]
