# Generated by Django 5.2.4 on 2025-07-23 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0008_remove_perfilusuario_cuestionarios_asignados_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='cuestionarios_asignados',
            field=models.ManyToManyField(blank=True, to='contabilidad.cuestionario'),
        ),
    ]
