# Generated by Django 5.2.4 on 2025-07-23 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0009_perfilusuario_cuestionarios_asignados'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resultadocuestionario',
            old_name='fecha_completado',
            new_name='fecha_inicio',
        ),
        migrations.AddField(
            model_name='resultadocuestionario',
            name='completado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='resultadocuestionario',
            name='puntaje',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='RespuestaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opcion_seleccionada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contabilidad.opcion')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contabilidad.pregunta')),
                ('resultado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='contabilidad.resultadocuestionario')),
            ],
        ),
    ]
